name: deploy

on:
  push:
    branches:
      - main
      
  pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
    
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - run: sudo rsync -av --delete-after . /var/www/victory-lp/

      - name: Linting
        run: bun lint

      - run: bun start:prod
